load_module /usr/lib/nginx/modules/ngx_http_brotli_static_module.so;
user nginx;
worker_processes 2;
error_log /dev/stderr warn;
pid /var/run/nginx.pid;
events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    types { application/manifest+json webmanifest; }
    default_type application/octet-stream;
    access_log off;
    sendfile on;
    keepalive_timeout 65;
    gzip on;
    gzip_min_length 512;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_vary on;
    gzip_static on;
    brotli_static on;
    include /etc/nginx/conf.d/*.conf;
}
